apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db-deployment
  namespace: my-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: my-db
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-db-secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-db-secret
                key: MONGO_INITDB_ROOT_PASSWORD

        volumeMounts:
          - name: mongo-volume
            mountPath: /data/db

      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: my-db-pvc
          
