apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-db-pvc
  namespace: my-app
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce